# Generated by Django 5.1.4 on 2025-08-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0007_remove_artist_latest_track_artist_latest_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/', verbose_name='Обложка')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('catalog_number', models.CharField(blank=True, max_length=50, verbose_name='Каталожный номер')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Артист')),
                ('genres', models.ManyToManyField(blank=True, to='music.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/', verbose_name='Аудио файл')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tracks/', verbose_name='Обложка')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('bpm', models.PositiveIntegerField(blank=True, null=True, verbose_name='BPM')),
                ('key', models.CharField(blank=True, max_length=10, verbose_name='Тональность')),
                ('track_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер трека')),
                ('spotify_url', models.URLField(blank=True, verbose_name='Spotify')),
                ('soundcloud_url', models.URLField(blank=True, verbose_name='SoundCloud')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('bandcamp_url', models.URLField(blank=True, verbose_name='Bandcamp')),
                ('beatport_url', models.URLField(blank=True, verbose_name='Beatport')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Количество прослушиваний')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_free_download', models.BooleanField(default=False, verbose_name='Бесплатное скачивание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='music.album', verbose_name='Релиз')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Артист')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['-release_date', 'track_number'],
                'unique_together': {('slug', 'artist')},
            },
        ),
    ]
