# Generated by Django 5.1.4 on 2025-08-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='track',
            name='key',
            field=models.CharField(blank=True, max_length=5, verbose_name='Тональность'),
        ),
    ]
