# Generated by Django 5.1.4 on 2025-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_genres_track_genres_alter_track_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.CharField(blank=True, help_text='Введите жанры через запятую (например: Techno, Industrial, EBM)', max_length=500, verbose_name='Жанры'),
        ),
    ]
