# Generated by Django 5.1.4 on 2025-08-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_is_featured_album_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genres',
        ),
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.CharField(blank=True, help_text='Введите жанры через запятую (например: Techno, Industrial, EBM)', max_length=500, verbose_name='Жанры'),
        ),
    ]
