# Generated by Django 5.1.4 on 2025-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_genres_remove_track_genres_track_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='catalog_number',
            field=models.CharField(blank=True, help_text='Необязательно. Например: CARNAGE001, EP001', max_length=50, verbose_name='Каталожный номер'),
        ),
    ]
