# Generated by Django 5.1.4 on 2025-08-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_catalog_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата релиза'),
        ),
    ]
