# Generated by Django 5.1.4 on 2025-08-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_remove_artist_latest_track_artist_latest_album'),
        ('music', '0006_alter_track_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Артист'),
        ),
    ]
