# Generated by Django 5.1.4 on 2025-08-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_artist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
