# Generated by Django 5.1.4 on 2025-08-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_track_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='apple_music_url',
            field=models.URLField(blank=True, verbose_name='Apple Music'),
        ),
    ]
