# Generated by Django 5.1.4 on 2025-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_album_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание релиза, включая описание каждого трека', verbose_name='Описание релиза'),
        ),
    ]
