version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=carnage_music_project.settings
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 carnage_music_project.wsgi:application"
    
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - web
    restart: unless-stopped
