services:
  - type: web
    name: carnage-music-website
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn carnage_music_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: carnage_music_project.settings_render
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: carnage-music-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: carnage-music-db
    databaseName: carnage_music
    user: carnage_user
    plan: starter
