# Generated by Django 5.1.4 on 2025-08-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.genre'),
        ),
        migrations.AlterUniqueTogether(
            name='artistfollow',
            unique_together={('user', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='artistgenre',
            unique_together={('artist', 'genre')},
        ),
    ]
