# Generated by Django 5.1.4 on 2025-08-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
