# Generated by Django 5.1.4 on 2025-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_tiktok_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, verbose_name='Слоган'),
        ),
    ]
