# Generated by Django 5.1.4 on 2025-08-08 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_artist_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='latest_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_artist', to='music.track', verbose_name='Последний релиз'),
        ),
    ]
