# Generated by Django 5.1.4 on 2025-08-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_latest_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artistgenre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistgenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='total_plays',
        ),
        migrations.DeleteModel(
            name='ArtistFollow',
        ),
        migrations.DeleteModel(
            name='ArtistGenre',
        ),
    ]
