# Generated by Django 5.1.4 on 2025-08-08 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artistgenre_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='latest_track',
        ),
        migrations.AddField(
            model_name='artist',
            name='latest_album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_artist', to='music.album', verbose_name='Последний релиз'),
        ),
    ]
