# Generated by Django 5.1.4 on 2025-08-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_remove_artist_latest_track_artist_latest_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='album_info',
            field=models.TextField(blank=True, help_text='Автоматически заполняется при выборе релиза', verbose_name='Информация о релизе'),
        ),
    ]
